services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8084:8084"
    environment:
      - REDIS_HOSTS=local:redis:6379
